/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/jodan.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="tonguelogo" geometry={nodes.tonguelogo.geometry} material={materials.logo} position={[0.75, 3.96, 3.09]} rotation={[0.03, -0.09, -1.3]} scale={0.84} />
        <mesh name="heel" geometry={nodes.heel.geometry} material={materials.heel} position={[-1.35, 3.15, 0.27]} />
        <mesh name="nike_tick" geometry={nodes.nike_tick.geometry} material={materials.tick} position={[0.58, 1.76, 1.19]} rotation={[1.58, 0, 0.01]} scale={0.19} />
        <mesh name="평면002" geometry={nodes.평면002.geometry} material={materials.side} position={[-0.13, 2.23, 0.92]} rotation={[1.29, 0, 0]} scale={0.45} />
        <mesh name="heel001" geometry={nodes.heel001.geometry} material={materials.side} position={[-1.35, 3.15, 0.27]} />
        <mesh name="평면004" geometry={nodes.평면004.geometry} material={materials.side} position={[-0.13, 2.23, 0.92]} rotation={[1.29, 0, 0]} scale={0.45} />
        <mesh name="laces" geometry={nodes.laces.geometry} material={materials.laces} position={[3.84, 0.83, -7.29]} rotation={[-1.48, 1.29, 1.5]} />
        <mesh name="실린더001" geometry={nodes.실린더001.geometry} material={materials.laces} position={[0.63, 3.1, -1.09]} rotation={[0.04, 0.11, 0.01]} scale={[0.03, 0.29, 0.03]} />
        <mesh name="OUTSOLE" geometry={nodes.OUTSOLE.geometry} material={materials.OUTSOLE} position={[8.21, 0.14, 0.49]} scale={[0.35, -0.35, 0.35]} />
        <mesh name="linear" geometry={nodes.linear.geometry} material={materials.path} position={[-1.33, 3.15, 0.26]} />
        <mesh name="toe_box" geometry={nodes.toe_box.geometry} material={materials.path} position={[4.13, 1.09, 1.27]} rotation={[Math.PI / 2, 0, 0]} scale={0.3} />
        <mesh name="서프_패치" geometry={nodes.서프_패치.geometry} material={materials.path} position={[2.29, 1.08, 0.48]} rotation={[1.43, -0.31, -0.07]} />
        <mesh name="평면" geometry={nodes.평면.geometry} material={materials.path} position={[1.26, 2.81, 1.27]} rotation={[1.59, -0.47, 0.01]} scale={0.15} />
        <mesh name="toe" geometry={nodes.toe.geometry} material={materials.toe} position={[4.1, 1.9, -0.07]} scale={2.4} />
        <mesh name="tongue" geometry={nodes.tongue.geometry} material={materials.toe} position={[0.76, 3.9, 3.09]} rotation={[0.05, -0.09, -1.26]} scale={0.84} />
        <mesh name="평면005" geometry={nodes.평면005.geometry} material={materials.toe} position={[1.74, 3.1, -0.03]} rotation={[0.03, 0, -0.5]} scale={[0.26, 0.26, 0.21]} />
        <mesh name="Midsole" geometry={nodes.Midsole.geometry} material={materials.midsole} position={[-2.02, 0.69, 0.61]} scale={0.36} />
        <mesh name="stitchmidsole" geometry={nodes.stitchmidsole.geometry} material={materials.midsole} position={[5.41, 0.69, 0.7]} scale={-0.08} />
        <mesh name="평면003" geometry={nodes.평면003.geometry} material={materials.heel} position={[-2.21, 2.8, 0.34]} rotation={[0, 0, -1.58]} scale={0.28} />
      </group>
    </group>
  )
}

useGLTF.preload('/jodan.glb')
